"""Backbone contracts: generated Pydantic models plus normative JSON Schema validation.

`models` is generated by `make codegen` and must not be hand-edited (CLAUDE.md §2.2).
"""

from cio_contracts.validators import (
    ContractViolation,
    bundle,
    contract_names,
    iter_errors,
    validate,
    validator_for,
)

__version__ = "0.1.0"

__all__ = [
    "ContractViolation",
    "__version__",
    "bundle",
    "contract_names",
    "iter_errors",
    "validate",
    "validator_for",
]
